services:
    Github\Client:
        class: Github\Client
        arguments:
            - null
            - 'machine-man-preview'
        calls:
            - ['authenticate', ['@github.jwt.token', null, !php/const Github\Client::AUTH_JWT]]
