version: "3.7"
services:
    web:
        image: rector-ci_org
        restart: unless-stopped
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=rector-ci_org"
        ports:
            - "8080:80"
        tmpfs:
            - /var/www/rector-ci.org/var/cache
        volumes:
            - .:/var/www/rector-ci.org:cached

    bistro:
        image: docker.pkg.github.com/rectorphp/docker-base-bistro-image-builder/bistro:latest
        working_dir: "/home/bistro/bistro"
        command:
            - "./cmake/Debug/server/bistro_scheduler"
            - "--http_server_port=6790"
            - "--worker_command=/home/bistro_task.sh"
            - "--data_dir=/tmp/bistro_scheduler"
            - "--status_table=task_statuses"
            - "--config_file=/home/bistro_config.json"
        ports:
            - "6790:6790"
        volumes:
            - "./.docker/bistro/bistro_task.sh:/home/bistro_task.sh"
            - "./.docker/bistro/data:/tmp/bistro_scheduler"
            - "./.docker/bistro/scheduler_config.json:/home/bistro_config.json"
