version: "3.7"
services:
    web:
        image: rector-ci_org
        restart: unless-stopped
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=rector-ci_org"
        ports:
            - "8080:80"
        tmpfs:
            - /var/www/rector-ci.org/var/cache
        volumes:
            - .:/var/www/rector-ci.org:cached
