parameters:
    locale: 'en'

    github:
        clientId: '%env(GITHUB_APP_CLIENT_ID)%'
        clientSecret: '%env(GITHUB_APP_CLIENT_SECRET)%'
        redirectUri: '%env(GITHUB_APP_REDIRECT_URI)%'

    repositoriesDirectory: '%kernel.project_dir%/%env(REPOSITORIES_DIRECTORY)%'
    rectorBinary: '%kernel.project_dir%/vendor/bin/rector'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Rector\RectorCI\:
        resource: '../src/*'
        exclude: '../src/{HttpKernel/RectorCIKernel.php,Entity,**/Exceptions,**/Entity}'

    Rector\RectorCI\GitHub\GithubJWTTokenFactory:
        arguments:
            - '%env(GITHUB_APP_ID)%'
            - '%env(GITHUB_APP_PRIVATE_KEY)%'


    github.jwt.token:
        class: Lcobucci\JWT\Token
        factory: ['@Rector\RectorCI\GitHub\GithubJWTTokenFactory', 'create']

    Rector\RectorCI\Controller\HomepageController:
        arguments:
            - '%env(GITHUB_APP_CLIENT_ID)%'

    League\OAuth2\Client\Provider\Github:
        arguments:
            - '%github%'

    Rector\RectorCI\GitRepository\GitRepositoryPathGetter:
        arguments:
            - '%repositoriesDirectory%'

    Rector\RectorCI\RectorSet\RectorSetRunner:
        arguments:
            - '%rectorBinary%'
