name: Main

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    - name: Cache warmup
                      run: bin/console cache:warmup

                    - name: PHPStan
                      run: composer run-script phpstan

                    - name: Easy Coding Standard
                      run: composer run-script check-cs

                    - name: Tests
                      run: vendor/bin/phpunit

        runs-on: ubuntu-latest
        name: ${{  matrix.actions.name}}

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress --ansi --no-script

            -   run: ${{ matrix.actions.run }}
